name = "lmpify2"
compatibility_date = "2025-04-21"
dev.port = 3000
main = "main.ts"
assets.directory = "./"
routes = [
  { pattern = "lmpify.com", custom_domain = true },
  { pattern = "www.lmpify.com", custom_domain = true }
]

kv_namespaces = [
  { binding = "RESULTS", id = "e698f458a5c0411b8998f335bd24dc11" }
]

[[durable_objects.bindings]]
name = "DORM_NAMESPACE"
class_name = "DORM"

[[durable_objects.bindings]]
name = "LMPIFY_DO"
class_name = "LmpifyDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DORM"]

[[migrations]]
tag = "v2"
new_classes = ["LmpifyDO"]