name = "codefromanywhere_extexe_main"
compatibility_date = "2024-10-11"
assets = { directory= "./public" }
main = "index.ts"

routes = [
  { pattern = "extexe.com", custom_domain = true },
  { pattern = "www.extexe.com", custom_domain = true }
]
