type: object
description: |
  Overwrite default settings. This settingsfile is recursively overwritten. Possible locations:

  1. githuq default.
  2. ❌ owner default at 'nlang-settings' repo nlang.yaml file.
  3. repo default at nlang.yaml at root.
  4. ❌ folder default at nlang.json in folder.

  This will make nlang very configurable, which is great for optimising for different goals. 
  Don't usage of this yet I don't know the important parameters yet. This is a draft.
additionalProperties: false
properties:
  enabled:
    type: boolean
    description: Enable nlang compilation. Enabled by default for nlang-authenticated users. For unauthenticated owner public repos, disabled by default.
  context:
    type: object
    description: Overwrite the context prompt and authentication needed to use different tools in the context retrieval step.
    properties:
      prompt:
        type: string
      auth:
        description: mapped object containing bearer authorization keys per domain. assumes https protocol. values are keys or null. if null, it will apply the available nlang auth which is a github access token tying to a github user.
        type: object
        default:
          llmtext.com: true
        additionalProperties:
          oneOf:
            - type: string
              description: the auth bearer token
            - type: boolean
              description: Will apply default nlang auth which is a github PAT
      llmBasePath:
        type: string
      llmModelName:
        type: string
      llmApiKey:
        type: string
  generation:
    description: Overwrite the prompt used for generating new assets at every step. Variables must use blockquote notation (e.g. [variable])
    type: object
    properties:
      prompt:
        type: string
      customTargetInstructions:
        description: Overwrite specific instructions per target extension
        type: object
        default:
          md: Write professionally
          ts: Use cloudflare worker ESM Typescript syntax. Do not use Node.js libs.
          html: Ensure to use tailwind and include <script src="https://cdn.tailwindcss.com"></script> in the head.
        additionalProperties:
          type: string
      llmBasePath:
        type: string
      llmModelName:
        type: string
      llmApiKey:
        type: string
